# Build images and scan it for security vulnerabilities
# Push built images to your personal or private repository on Docker Hub

# -20 Postgres container is not configured as dependency for application container ????
# -20 docker-compose.yml contains hardcoded variablesь

version: '3.8'

services:
  server:
    build:
      context: .
#    command: sh -c "npm run start:dev"
    # связываем порты внутри контейнера с портом снаружи. как прокидывать порт переменной окружения?
    # может быть здесь объявить переменную и прокинуть в код
    ports:
      - '4000:4000'
    # это мы связываем локальную директорию с той, в которую будет скопировано приложение
    networks:
      - home-library
    volumes:
      - ./src:/usr/src/app/src
    restart: always
    environment:
      DB_PASSWORD: secret
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_DB: home-library
#    depends_on:
#      db:
#        condition: service_healthy
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    user: postgres
    networks:
      - home-library
    # это куда данные будут сохраняться для того чтобы переиспользовать их при перезапуске контейнера
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: home-library
#    healthcheck:
#      test: [ "CMD", "pg_isready" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

networks:
  home-library:

volumes:
  db-data: